package vdm.p1.logic.scenes;

import vdm.p1.engine.IEngine;
import vdm.p1.engine.IFont;
import vdm.p1.engine.ISensors;
import vdm.p1.engine.ISound;
import vdm.p1.engine.ShakeListener;
import vdm.p1.logic.GameTheme;
import vdm.p1.logic.objects.LifeManager;
import vdm.p1.logic.objects.Table;
import vdm.p1.logic.objects.buttons.CheckSolutionButton;
import vdm.p1.logic.objects.buttons.GoToStartSceneButton;
import vdm.p1.logic.objects.buttons.GoToThemeLevelSelectButton;

public final class GameScene extends Scene {
	private final ISound sound;
	private final IFont font;
	private final Table table;
	private ShakeListener shakeListener = null;

	public GameScene(IEngine engine, GameTheme theme, String level) {
		super(engine);

		font = engine.getGraphics().newFont("font/pico.ttf", 10, true);
		IFont tableFont = engine.getGraphics().newFont("font/pico.ttf", 7, false);
		sound = engine.getAudio().createSound("audio/meadow_thoughts");
		engine.getAudio().playSound(sound);

		LifeManager lifeManager = (LifeManager) new LifeManager(engine, font).setPosition(130, 100).setSize(140, 40);
		table = (Table) Table.fromFile(tableFont, lifeManager, theme, level).setPosition(50, 150).setSize(300, 300);

		addGameObject(lifeManager);
		addGameObject(table);

		addButton(new GoToThemeLevelSelectButton(getEngine(), theme), engine.getGraphics().newImage("image/grey_boxCross.png"), font, "Rendirse", 20, 20);
	}

	public GameScene(IEngine engine, int rows, int columns) {
		super(engine);

		font = engine.getGraphics().newFont("font/pico.ttf", 10, true);
		IFont tableFont = engine.getGraphics().newFont("font/pico.ttf", 7, false);
		sound = engine.getAudio().createSound("audio/meadow_thoughts");
		engine.getAudio().playSound(sound);

		LifeManager lifeManager = (LifeManager) new LifeManager(engine, font).setPosition(130, 100).setSize(140, 40);
		table = (Table) Table.fromRandom(tableFont, lifeManager, rows, columns).setPosition(50, 150).setSize(300, 300);

		addGameObject(lifeManager);
		addGameObject(table);

		addButton(new GoToStartSceneButton(getEngine()), engine.getGraphics().newImage("image/grey_boxCross.png"), font, "Rendirse", 20, 20);
		addButton(new CheckSolutionButton(getEngine(), table), engine.getGraphics().newImage("image/grey_boxCheckmark.png"), font, "Comprobar", 260, 20);
	}

	@Override
	public void init() {
		ISensors sensors = getEngine().getSensors();
		// If there are sensors available, and the table doesn't have a name (autogenerated level),
		// then register the shake listener to shuffle the table.
		if (sensors != null && table.getName() == null) {
			shakeListener = new ShakeListener() {
				@Override
				public void onShake(double acceleration) {
					table.prepareShuffle();
				}
			};
			sensors.registerListener(shakeListener);
		}

		super.init();
	}

	@Override
	public void dispose() {
		super.dispose();
		getEngine().getAudio().stopSound(sound);

		ISensors sensors = getEngine().getSensors();
		if (sensors != null && shakeListener != null) {
			sensors.unregisterListener(shakeListener);
		}
	}
}
